"""
deterministic_proposal_provider.py
Single responsibility: produce Proposal objects using the rule-based
scout strategy (Optuna TPE, grid search, or random). No LLM calls.
"""

from __future__ import annotations

import logging

import research_lab
from proposal_engine import Proposal, ProposalContext

logger = logging.getLogger(__name__)


class DeterministicProposalProvider:
    def __init__(self, search_module, config: dict):
        self._search = search_module
        self._config = config

    def get_proposals(self, context: ProposalContext, n: int = 3) -> list[Proposal]:
        candidates = research_lab.scout_experiments(
            brief=dict(context.config.get("brief", {})),
            lab_state=dict(context.config.get("lab_state", {})),
            available_models=dict(context.config.get("available_models", {})),
            experiment_memory=dict(context.config.get("memory_payload", {})),
            current_best=dict(context.best_metrics),
            scout_limit=n,
            exploit_delta_ratio=float(context.config.get("exploit_delta_ratio", 0.15)),
        )
        return [
            Proposal(
                hypothesis=c.get("description", "deterministic candidate"),
                hyperparameters=c.get("params", {}),
                rationale="generated by deterministic search",
                source="deterministic",
                confidence=0.7,
                raw=c,
            )
            for c in candidates
        ]
