"""Normalize provider outputs into one validated proposal shape."""

from __future__ import annotations

import json
from typing import Any

from proposal_gates import normalize_research_proposal_to_candidate, validate_research_proposal


def normalize_deterministic_candidate(
    raw_candidate: dict[str, Any],
    *,
    available_models: dict[str, dict[str, Any]],
    candidate_index: int,
    proposal_source: str,
    proposal_status: str,
    backend: str,
) -> dict[str, Any]:
    proposal = _build_deterministic_research_proposal(raw_candidate)
    validated = validate_research_proposal(
        proposal,
        available_models=available_models,
        backend_name=backend,
    )
    normalized = normalize_research_proposal_to_candidate(
        proposal=validated,
        available_models=available_models,
        candidate_index=candidate_index,
        backend=backend,
        model="deterministic",
        prompt_hash="",
    )
    normalized["experiment_id"] = str(raw_candidate.get("experiment_id", f"deterministic-scout-{candidate_index:03d}"))
    normalized["stage"] = str(raw_candidate.get("stage", "scout"))
    normalized["proposal_family"] = str(raw_candidate.get("proposal_family", normalized["proposal_family"]))
    normalized["proposal_source"] = proposal_source
    normalized["proposal_status"] = proposal_status
    normalized["proposal_backend"] = backend
    normalized["proposal_model"] = None
    normalized["prompt_hash"] = None
    normalized["confidence"] = float(validated["confidence"])
    return normalized


def normalize_llm_candidate(
    raw_candidate: dict[str, Any],
    *,
    available_models: dict[str, dict[str, Any]],
    candidate_index: int,
    backend: str,
    model: str | None,
) -> dict[str, Any]:
    research_proposal = raw_candidate.get("research_proposal")
    validated = validate_research_proposal(
        research_proposal,
        available_models=available_models,
        backend_name=backend,
    )
    normalized = normalize_research_proposal_to_candidate(
        proposal=validated,
        available_models=available_models,
        candidate_index=candidate_index,
        backend=backend,
        model=str(model or raw_candidate.get("proposal_model") or ""),
        prompt_hash=str(raw_candidate.get("prompt_hash", "")),
    )
    normalized["experiment_id"] = str(raw_candidate.get("experiment_id", normalized["experiment_id"]))
    normalized["stage"] = str(raw_candidate.get("stage", normalized["stage"]))
    normalized["proposal_family"] = str(raw_candidate.get("proposal_family", normalized["proposal_family"]))
    normalized["proposal_source"] = str(raw_candidate.get("proposal_source", normalized["proposal_source"]))
    normalized["proposal_status"] = str(raw_candidate.get("proposal_status", normalized["proposal_status"]))
    normalized["proposal_backend"] = raw_candidate.get("proposal_backend", backend)
    normalized["proposal_model"] = raw_candidate.get("proposal_model", model)
    normalized["prompt_hash"] = raw_candidate.get("prompt_hash")
    normalized["confidence"] = float(raw_candidate.get("confidence", normalized["confidence"]))
    if raw_candidate.get("expected_delta_rmse") is not None:
        normalized["expected_delta_rmse"] = raw_candidate.get("expected_delta_rmse")
    return normalized


def _build_deterministic_research_proposal(raw_candidate: dict[str, Any]) -> dict[str, Any]:
    model_name = str(raw_candidate.get("model_name", "")).strip()
    params = dict(raw_candidate.get("params", {}))
    description = str(
        raw_candidate.get("description")
        or raw_candidate.get("hypothesis")
        or "Deterministic search candidate."
    ).strip()
    return {
        "hypothesis": description,
        "rationale": "Generated by the deterministic scout strategy over the configured search space.",
        "change_type": "other",
        "target_component": model_name,
        "proposed_change": json.dumps(params, sort_keys=True),
        "expected_direction": "uncertain",
        "expected_metric_effect": {
            "metric": "rmse",
            "direction": "down",
            "magnitude_estimate": "unknown",
        },
        "confidence": float(raw_candidate.get("confidence", 0.0)),
        "novelty_claim": "Generated from deterministic search over executable configurations.",
        "risk_notes": "Deterministic proposal without language-model rationale.",
        "candidate_config": {
            "model_name": model_name,
            "params": params,
        },
    }
